### ISSUE TITLE
cannot find my_sample.visium.raw_matrix.genus.csv

### ISSUE THREAD

**Issue by NicolaasVanRenne** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#2] opened 2023-01-10 22:56 UTC
Hello, 
I'm trying to run your Visium pipeline. I ran Visium_pipeline.sh on my visium sample (that employs UMI_annotator.py - which is also provided).

I get the python output and the pathseq output, however, I do not see my_sample.visium.raw_matrix.genus.csv anywhere. I need this file in the next pipeline: Visium.R

The tutorial also talks about Pipeline_Visium.sh which is not provided -or it is the same as Visium_pipeline.sh. Could you confirm this or is there a Pipeline_Visium.sh? Confusing...

But again; which part of the code should yield my_sample.visium.raw_matrix.genus.csv? I do not see that anywhere in the code provided, or am I missing something. 

Thanks for your help, I really feel lost here...

Nicolaas

**Comment by hanruiw** [comment] 2023-01-11 19:20
Dear Nicolaas, sorry for confusion, I updated the name of pipeline in readme.md. In addition, could you please show me the list of output file from the python script?

**Comment by NicolaasVanRenne** [comment] 2023-01-11 19:55
thanks for answering so quickly, much appreciated!

This is my python folder. Maybe it is simply malfunctioning on my sample, and I could try and reproduce your dataset first...

![image](https://user-images.githubusercontent.com/48249789/211904593-8ecc9032-07a8-4c63-8193-f5cb7ac02c91.png)

Could you share what I should get if it's running correctly? 

Thanks! Nicolaas

**Comment by hanruiw** [comment] 2023-01-11 21:16
Hi, could you please check if the PathSeq output is not empty? I will try to reproduce this issue on my side and get back to you.

**Comment by NicolaasVanRenne** [comment] 2023-01-11 23:05
It is not empty: here are the files in the pathseq directory

![image](https://user-images.githubusercontent.com/48249789/211937125-6e69ec34-2a3d-4cc9-bf04-012dc36c2431.png)

**Comment by hanruiw** [comment] 2023-01-12 19:12
Dear Nicolaas, I reran UMI_annotator.py :
![图片](https://user-images.githubusercontent.com/61566114/212159269-c1b27be8-09f4-4741-9429-b001cd563b2d.png)
and works fine on my side: 
![图片](https://user-images.githubusercontent.com/61566114/212158735-43cecddf-7036-4ae4-8e97-f9875fd257ec.png)

**Comment by NicolaasVanRenne** [comment] 2023-01-13 10:36
So while the Visium.R code talks about my_sample.visium.**raw**_matrix.genus.csv as shown below...

>     metadata_file = paste0(processed_foler,'/',each_sample,'.visium.raw_matrix.genus.csv')

This should actually be my_sample.visium.**filtered**_matrix.genus.csv

Is that correct? Confusing!

If so, then my .genus.csv file is empty... Maybe there are no bacterial reads in my sample? 

I have mapped the CRC_16 sample with spaceranger and I am now trying to replicate the work.  Let's see if that one works and work up from there.

Thank you Hanrui for your kind support

**Comment by hanruiw** [comment] 2023-01-13 17:29
Dear Nicolaas, sorry for confusion, I updated the pipeline code to output ''raw_matrix' instead of 'filtered_matrix' and will correct the output names. The difference between raw matrix and filtered matrix is whether the calculation is based on 'capture spots' instead of 'all spots on the slide'. However, this does not affect our analysis because we used filtered_feature_bc_matrix/barcodes.tsv.gz in Seurat, so any spots other than capture spots are not counted. 
In our pipeline, unmapped reads with UB/CB tags from Spaceranger bam file and YP tag from PathSeq (connected based on read names) will be extracted to `.readnamepath` file, so if your `.readnamepath` file is empty, maybe it's because there's no reads have UB/CB tags and YP tag at the same. I think if you lower the Pathseq thresholds you will get larger number of bacteria reads (PathSeq help: https://gatk.broadinstitute.org/hc/en-us/articles/9570234210075-PathSeqPipelineSpark and https://gatk.broadinstitute.org/hc/en-us/articles/360035889911--How-to-Run-the-Pathseq-pipeline)

**Comment by NicolaasVanRenne** [comment] 2023-01-16 13:53
Hello again,

I'm not sure about my outcome. I get bacterial reads if I set my , but most of hem lack a YP-tag (not sure what YP tag means).

I set: 
--min-clipped-read-length 31
--min-score-identity .7

I think 31 is the lowest setting possible but not sure here... min score .7 but also unsure if it is low enough...

For my sample_XXX I get the following outcome: 

> sample_XXX
> [W::hts_idx_load2] The index file is older than the data file: /
> sample_XXX/outs/possorted_genome_bam.bam.bai
> len(dict_for_genus) =  3608
> Total reads in pathseq bam =  4347879
> Total reads in pathseq bam with YP tag  =  10635
> total cellranger bam reads =  213903991
> total cellranger bam reads with UB CB tags (in-cell) =  185496985
> total UNMAPPED cellranger bam reads with UB CB tags (in-cell) =  10047351
> total cellranger reads with UB_CB_unmap Aligned to Pathseq reads with YP tags = (in-cell) 8489
> Total unambigious UMI =  7897
> total pathogen-associated gems =  2336
> total filtered pathogen-associated cells =  2336
> total number of cells =  2499


In the pathseq/sample_XXX.pathseq.complete.csv file I have all the reads listed:
![image](https://user-images.githubusercontent.com/48249789/212691950-7a946485-6ec8-469c-96f4-c984aa7e2dd2.png)

The virus reads are probably a false positive, but the bacteria might be real (or also false positive). In any case, in python/sample_XXX.visium.filtered_matrix.genus.csv, these bacterial reads are all lost. Where did they all go? Are they associatd with spots that are not retained in the spatial coordinates (and thus 100% sure false positive reads), or don't they appear on my barcodes for some settings I can adjust?

![image](https://user-images.githubusercontent.com/48249789/212692883-cc9dd463-e87d-4dc1-b088-5728c0544163.png)

Probably there are just not enough "Total cellranger reads with UB_CB_unmap Aligned to Pathseq reads with YP tags" but what does it mean, and how can I increase them? 

Below is the replication of the CRC_16 sample. Here you see a lot of UB_CB_unmap Aligned to Pathseq reads with YP tags.

> sample_CRC_16
> len(dict_for_genus) =  18470
> Total reads in pathseq bam =  6279876
> Total reads in pathseq bam with YP tag  =  2645265
> total cellranger bam reads =  174436315
> total cellranger bam reads with UB CB tags (in-cell) =  143746173
> total UNMAPPED cellranger bam reads with UB CB tags (in-cell) =  9439887
> total cellranger reads with UB_CB_unmap Aligned to Pathseq reads with YP tags = (in-cell) 1309914
> Total unambigious UMI =  84171
> total pathogen-associated gems =  1418
> total filtered pathogen-associated cells =  1418
> total number of cells =  3104
>


Any idea's or suggestions?

Thank you 

Nicolaas

**Comment by hanruiw** [comment] 2023-01-16 20:11
Dear Nicolaas,

Reads from SpaceRanger bam file are assigned 'UB' and 'CB' tags (corrected UMI/barcode), then reads from PathSeq bam file are assigned 'YP' tag (pathogen annotation), and only unmapped reads contain 'UB', 'CB' and 'YP' tag will be extracted to `.readnamepath` file. 
I would suggest you to extract unmapped reads with  'UB' and 'CB' tags from Spaceranger bam file and rerun PathSeq on those reads to validate the result. 
The detection of bacteria is associated with many factors, not all tissue contains high bacteria load. Unfortunately I'm not a wet lab person, I would suggest you to contact Prof. Susan Bullman or Dr. Jorge L Galeano for more details about tissue selection and wet lab process.

Best regards,
Hanrui

**Comment by hanruiw** [comment] 2023-01-18 17:55
Dear Nicolaas,

I'm going to close this issue, if you have any questions please don't hesitate reopen it and let me know.

Best wishes,
Hanrui

**Closed by hanruiw** 2023-01-18 17:55 UTC
